export const products = [
  {
    name: "1",
    price: "40.0",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "2",
    price: "80.0",
    photo_ref: "none",
    description: "Double Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "3",
    price: "55.0",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Half Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "4",
    price: "110.0",
    photo_ref: "none",
    description: "Double Layer",
    category: "Cake",
    subcategory: "Half Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "5",
    price: "85.0",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Full Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "6",
    price: "35",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Six Inches",
    theme: "Round Cake",
  },
  {
    name: "7",
    price: "45.0",
    photo_ref: "none",
    description: "Double Layer",
    subcategory: "Six Inches",
    theme: "Round Cake",
  },
  {
    name: "8",
    price: "60.0",
    photo_ref: "none",
    description: "Triple Layer",
    category: "Cake",
    subcategory: "Six Inches",
    theme: "Round Cake",
  },
  {
    name: "9",
    price: "35",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Eight Inches",
    theme: "Round Cake",
  },
  {
    name: "10",
    price: "45",
    photo_ref: "none",
    description: "Double Layer",
    category: "Cake",
    subcategory: "Eight Inches",
    theme: "Round Cake",
  },
  {
    name: "11",
    price: "60",
    photo_ref: "none",
    description: "Tripple Layer",
    category: "Cake",
    subcategory: "Eight Inches",
    theme: "Round Cake",
  },
  {
    name: "12",
    price: "40",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Ten Inches",
    theme: "Round Cake",
  },
  {
    name: "13",
    price: "80",
    photo_ref: "none",
    description: "Double Layer",
    category: "Cake",
    subcategory: "Ten Inches",
    theme: "Round Cake",
  },
  {
    name: "14",
    price: "0",
    photo_ref: "none",
    description:
      "Chocolate, White, Marble, Yellow, Red Velvet, Strawberry, and Tres Leches",
    category: "Cake",
    subcategory: "Cake Flavors",
    theme: "Custom Cake",
  },
  {
    name: "15",
    price: "0",
    photo_ref: "none",
    description:
      "American Buttercream, Whipped Icing, Peanut Butter Buttercream, Cream Cheese, Cookies and Cream",
    category: "Cake",
    subcategory: "Icing Flavors",
    theme: "Custom Cake",
  },
  {
    name: "16",
    price: "0",
    photo_ref: "none",
    description:
      "Strawberry, Bavarian, Chocolate Ganache, $5 extra depending on size of cake",
    category: "Cake",
    subcategory: "Fillings",
    theme: "Custom Cake",
  },
  {
    name: "17",
    price: "2.5",
    photo_ref: "none",
    description: "Churro",
    category: "Cookie",
    subcategory: "Gourmet",
    theme: "Gourmet",
  },
  {
    name: "18",
    price: "2.5",
    photo_ref: "none",
    description: "Monster",
    category: "Cookie",
    subcategory: "Gourmet",
    theme: "Gourmet",
  },
  {
    name: "19",
    price: "2.5",
    photo_ref: "none",
    description: "Twix",
    category: "Cookie",
    subcategory: "Gourmet",
    theme: "Gourmet",
  },
  {
    name: "20",
    price: "2.5",
    photo_ref: "none",
    description: "Turtle",
    category: "Cookie",
    subcategory: "Gourmet",
    theme: "Gourmet",
  },
  {
    name: "21",
    price: "2.5",
    photo_ref: "none",
    description: "Triple Chocolate",
    category: "Cookie",
    subcategory: "Gourmet",
    theme: "Gourmet",
  },
  {
    name: "22",
    price: "2.5",
    photo_ref: "none",
    description: "White Chocolate Macadamia Nut",
    category: "Cookie",
    subcategory: "Gourmet",
    theme: "Gourmet",
  },
  {
    name: "23",
    price: "2.5",
    photo_ref: "none",
    description: "Cookies and Cream",
    category: "Cookie",
    subcategory: "Gourmet",
    theme: "Gourmet",
  },
  {
    name: "24",
    price: "6",
    photo_ref: "none",
    description: "Make it a Sandwhich!",
    category: "Cookie",
    subcategory: "Gourmet",
    theme: "Gourmet",
  },
  {
    name: "25",
    price: "1.5",
    photo_ref: "none",
    description: "Chocolate Chip",
    category: "Cookie",
    subcategory: "Classic",
    theme: "Classic",
  },
  {
    name: "26",
    price: "1.5",
    photo_ref: "none",
    description: "Red Velvet",
    category: "Cookie",
    subcategory: "Classic",
    theme: "Classic",
  },
  {
    name: "27",
    price: "1.5",
    photo_ref: "none",
    description: "Chocolate Chunk",
    category: "Cookie",
    subcategory: "Quarter Sheet",
    theme: "Classic",
  },
  {
    name: "28",
    price: "1.5",
    photo_ref: "none",
    description: "Oatmeal",
    category: "Cookie",
    subcategory: "Classic",
    theme: "Classic",
  },
  {
    name: "29",
    price: "1.5",
    photo_ref: "none",
    description: "Oatmeal Raisin",
    category: "Cookie",
    subcategory: "Classic",
    theme: "Classic",
  },
  {
    name: "30",
    price: "1.5",
    photo_ref: "none",
    description: "Snickerdoodle",
    category: "Cookie",
    subcategory: "Classic",
    theme: "Classic",
  },
  {
    name: "31",
    price: "1.5",
    photo_ref: "none",
    description: "M&M",
    category: "Cookie",
    subcategory: "Classic",
    theme: "Classic",
  },
  {
    name: "32",
    price: "1.5",
    photo_ref: "none",
    description: "Peanut Butter",
    category: "Cookie",
    subcategory: "Classic",
    theme: "Classic",
  },
  {
    name: "33",
    price: "1.5",
    photo_ref: "none",
    description: "Sugar",
    category: "Cookie",
    subcategory: "Classic",
    theme: "Classic",
  },
  {
    name: "34",
    price: "4",
    photo_ref: "none",
    description: "Make it a Sandwich!",
    category: "Cookie",
    subcategory: "Classic",
    theme: "Classice",
  },
  {
    name: "35",
    price: "3",
    photo_ref: "none",
    description: "Chocolate Chip",
    category: "Pastry",
    subcategory: "Pastry",
    theme: "Pastry",
  },
  {
    name: "35",
    price: "3",
    photo_ref: "none",
    description: "Blueberry Muffins",
    category: "Pastry",
    subcategory: "Pastry",
    theme: "Pastry",
  },
  {
    name: "36",
    price: "3.5",
    photo_ref: "none",
    description: "Brownies",
    category: "Pastry",
    subcategory: "Pastry",
    theme: "Pastry",
  },
  {
    name: "37",
    price: 4,
    photo_ref: "none",
    description: "Cinnamon Rolls",
    category: "Pastry",
    subcategory: "Pastry",
    theme: "Pastry",
  },
  {
    name: "38",
    price: "2.5",
    photo_ref: "none",
    description: "Coffee Cake Slice",
    category: "Pastry",
    subcategory: "Pastry",
    theme: "Pastry",
  },
  {
    name: "39",
    price: "2.5",
    photo_ref: "none",
    description: "Chocolate",
    category: "Cupcake",
    subcategory: "Cupcake",
    theme: "Cupcake",
  },
  {
    name: "40",
    price: "2.5",
    photo_ref: "none",
    description: "Peanut Butter",
    category: "Cupcake",
    subcategory: "Cupcake",
    theme: "Cupcake",
  },
  {
    name: "41",
    price: "2.5",
    photo_ref: "none",
    description: "Red Velvet",
    category: "Cupcake",
    subcategory: "Cupcake",
    theme: "Cupcake",
  },
  {
    name: "42",
    price: "2.5",
    photo_ref: "none",
    description: "Birthday Cake",
    category: "Cupcake",
    subcategory: "Cupcake",
    theme: "Cupcake",
  },
  {
    name: "43",
    price: "2.5",
    photo_ref: "none",
    description: "Cookies and Cream",
    category: "Cupcake",
    subcategory: "Cupcake",
    theme: "Cupcake",
  },
  {
    name: "44",
    price: "1.25",
    photo_ref: "none",
    description: "Long Johns",
    category: "Donut",
    subcategory:
      "Chocolate, Maple, White Icing. Filling: No Filling, Bararian, or Fluffly",
    theme: "Donut",
  },
  {
    name: "45",
    price: "1.75",
    photo_ref: "none",
    description: "Bismarks",
    category: "Donut",
    subcategory: "White, Powder, or Glaze. Filling: Only Raspberry",
    theme: "Donut",
  },
  {
    name: "46",
    price: "1.75",
    photo_ref: "none",
    description: "Boston Cream Donuts",
    category: "Donut",
    subcategory: "Chocolate Icing with Bararian Filling",
    theme: "Donut",
  },
  {
    name: "47",
    price: "1.25",
    photo_ref: "none",
    description: "Yeast Donuts",
    category: "Donut",
    subcategory:
      "Glaze, White, Maple, Chocolate, Cinammon Sugar, or Powdered Sugar",
    theme: "Donut",
  },
  {
    name: "48",
    price: "2.5",
    photo_ref: "none",
    description: "Donut Holes",
    category: "Donut",
    subcategory: "Glazed Only, Price per Dozen",
    theme: "Donut",
  },
  {
    name: "49",
    price: "1.25",
    photo_ref: "none",
    description: "Cake Donuts",
    category: "Donut",
    subcategory: "Chocolate, Funfetti, Old Fashioned",
    theme: "Donut",
  },
  {
    name: "50",
    price: "1.75",
    photo_ref: "none",
    description: "Twists",
    category: "Donut",
    subcategory: "Maple, Chocolate, or Glaze",
    theme: "Donut",
  },
  {
    name: "51",
    price: "1.75",
    photo_ref: "none",
    description: "Apple Fritters",
    category: "Donut",
    subcategory: "",
    theme: "Donut",
  },
  {
    name: "52",
    price: "1.75",
    photo_ref: "none",
    description: "Peanut Butter Pretzel",
    category: "Donut",
    subcategory: "",
    theme: "Donut",
  },
  {
    name: "53",
    price: "1.75",
    photo_ref: "none",
    description: "Twists",
    category: "Donut",
    subcategory: "Maple, Chocolate, or Glaze",
    theme: "Donut",
  },
  {
    name: "54",
    price: "2.5",
    photo_ref: "none",
    description: "Americano",
    category: "Drink",
    subcategory: "Esspresso",
    theme: "Esspresso",
  },
  {
    name: "55",
    price: "3.5",
    photo_ref: "none",
    description: "Latte",
    category: "Drink",
    subcategory: "Esspresso",
    theme: "Esspresso",
  },
  {
    name: "56",
    price: "4.25",
    photo_ref: "none",
    description: "Carmel Machiato",
    category: "Drink",
    subcategory: "Espresso",
    theme: "Espresso",
  },

  {
    name: "57",
    price: "3.75",
    photo_ref: "none",
    description: "Mocha",
    category: "Drink",
    subcategory: "Espresso",
    theme: "Espresso",
  },

  {
    name: "58",
    price: "2",
    photo_ref: "none",
    description: "Espresso",
    category: "Drink",
    subcategory: "Espresso",
    theme: "Espresso",
  },

  {
    name: "59",
    price: "1.75",
    photo_ref: "none",
    description: "Onyx",
    category: "Drink",
    subcategory: "Coffee",
    theme: "Coffee",
  },

  {
    name: "60",
    price: "3.5",
    photo_ref: "none",
    description: "Onyx Bottomless Cup",
    category: "Drink",
    subcategory: "Coffee",
    theme: "Coffee",
  },
  {
    name: "61",
    price: "4",
    photo_ref: "none",
    description: "Pour Over",
    category: "Drink",
    subcategory: "Coffee",
    theme: "Coffee",
  },
  {
    name: "61",
    price: "3.25",
    photo_ref: "none",
    description: "Chai Latte",
    category: "Drink",
    subcategory: "Non Coffee",
    theme: "Non Coffee",
  },
  {
    name: "62",
    price: "3",
    photo_ref: "none",
    description: "Chai Tea",
    category: "Drink",
    subcategory: "Non Coffee",
    theme: "Non Coffee",
  },

  {
    name: "63",
    price: "3.25",
    photo_ref: "none",
    description: "London Fog",
    category: "Drink",
    subcategory: "Non Coffee",
    theme: "Non Coffee",
  },

  {
    name: "64",
    price: "3.75",
    photo_ref: "none",
    description: "Frappes",
    category: "Drink",
    subcategory: "Non Coffee",
    theme: "Non Coffee",
  },

  {
    name: "65",
    price: "4",
    photo_ref: "none",
    description: "Crush Fruit Smoothies",
    category: "Drink",
    subcategory: "Non Coffee",
    theme: "Non Coffee",
  },

  {
    name: "66",
    price: "1.75",
    photo_ref: "none",
    description: "Iced Tea",
    category: "Drink",
    subcategory: "Non Coffee",
    theme: "Non Coffee",
  },

  {
    name: "67",
    price: "2.5",
    photo_ref: "none",
    description: "Loose Leaf",
    category: "Drink",
    subcategory: "Non Coffee",
    theme: "Non Coffee",
  },
  {
    name: "68",
    price: "0.45",
    photo_ref: "none",
    description: "House Made Syrups",
    category: "Drink",
    subcategory: "Extras",
    theme: "Extras",
  },
  {
    name: "69",
    price: "0.25",
    photo_ref: "none",
    description: "Syrups",
    category: "Drink",
    subcategory: "Extras",
    theme: "Extras",
  },

  {
    name: "70",
    price: "0.75",
    photo_ref: "none",
    description: "Milks",
    category: "Drink",
    subcategory: "Extras",
    theme: "Extras",
  },

  {
    name: "71",
    price: "0.75",
    photo_ref: "none",
    description: "Extra Shot",
    category: "Drink",
    subcategory: "Extras",
    theme: "Extras",
  },
  {
    name: "72",
    price: "1.25",
    photo_ref: "none",
    description: "Canned Soda",
    category: "Drink",
    subcategory: "Extras",
    theme: "Extras",
  },
];
