export const products = [
  {
    name: "1",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "2",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "3",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "4",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "5",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "6",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "7",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "8",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "9",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "10",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "11",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "12",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "13",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "14",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "15",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "16",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "17",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "18",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "19",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "20",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "21",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "22",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "23",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "24",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "25",
    price: 420.69,
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  }
];