export const products = [
  {
    name: "1",
    price: "40.0",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "2",
    price: "80.0",
    photo_ref: "none",
    description: "Double Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "3",
    price: "55.0",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Half Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "4",
    price: "110.0",
    photo_ref: "none",
    description: "Double Layer",
    category: "Cake",
    subcategory: "Half Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "5",
    price: "85.0",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Full Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "6",
    price: "35",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Six Inches",
    theme: "Round Cake",
  },
  {
    name: "7",
    price: "45.0",
    photo_ref: "none",
    description: "Double Layer",
    subcategory: "Six Inches",
    theme: "Round Cake",
  },
  {
    name: "8",
    price: "60.0",
    photo_ref: "none",
    description: "Triple Layer",
    category: "Cake",
    subcategory: "Six Inches",
    theme: "Round Cake",
  },
  {
    name: "9",
    price: "35",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Eight Inches",
    theme: "Round Cake",
  },
  {
    name: "10",
    price: "45",
    photo_ref: "none",
    description: "Double Layer",
    category: "Cake",
    subcategory: "Eight Inches",
    theme: "Round Cake",
  },
  {
    name: "11",
    price: "60",
    photo_ref: "none",
    description: "Tripple Layer",
    category: "Cake",
    subcategory: "Eight Inches",
    theme: "Round Cake",
  },
  {
    name: "12",
    price: "40",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Ten Inches",
    theme: "Round Cake",
  },
  {
    name: "13",
    price: "80",
    photo_ref: "none",
    description: "Double Layer",
    category: "Cake",
    subcategory: "Ten Inches",
    theme: "Round Cake",
  },
  {
    name: "14",
    price: "0",
    photo_ref: "none",
    description: "Chocolate, White, Marble, Yellow, Red Velvet, Strawberry, and Tres Leches",
    category: "Cake",
    subcategory: "Cake Flavors",
    theme: "Custom Cake",
  },
  {
    name: "15",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "16",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "17",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "18",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "19",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "20",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "21",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "22",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "23",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "24",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "25",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Cake",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
  {
    name: "26",
    price: "420.69",
    photo_ref: "none",
    description: "Single Layer",
    category: "Drink",
    subcategory: "Quarter Sheet",
    theme: "Sheet Cake",
  },
];
